CREATE DATABASE Clinicas;

USE Clinicas;

--criado tabelas do bd

CREATE TABLE Clinicas
(
	IdClinica	INT PRIMARY KEY IDENTITY
	,Nome	VARCHAR(50)NOT NULL
	,Endereco	VARCHAR(50)NOT NULL
);

CREATE TABLE Veterinarios
(
	IdVeterinario	INT PRIMARY KEY IDENTITY
	,IdClinica	INT FOREIGN KEY REFERENCES Clinicas(idClinica)NOT NULL
	,Nome	VARCHAR(500)NOT NULL
	,CRMV VARCHAR(15)NOT NULL
);

CREATE TABLE Tipos
(
	IdTipo	INT PRIMARY KEY IDENTITY
	,TipoPEt VARCHAR(15)NOT NULL
);

CREATE TABLE Racas
(
	IdRaca		INT PRIMARY KEY IDENTITY
	,IdTipo	  INT FOREIGN KEY REFERENCES tipos(IdTipo)NOT NULL
	,NomeRaca	VARCHAR(15)NOT NULL
);

CREATE TABLE Donos
(
	IdDono	INT PRIMARY KEY IDENTITY
	,Nome	VARCHAR(500)NOT NULL
);

CREATE TABLE Pets
(
	IdPet	INT PRIMARY KEY IDENTITY
	,IdDono	INT FOREIGN KEY REFERENCES Donos(IdDono)NOT NULL
	,IdRaca	INT FOREIGN KEY REFERENCES Racas(IdRaca)NOT NULL
	,Nome	VARCHAR(50)NOT NULL
	,DataNascimento DATE NOT NULL
	,Telefone	VARCHAR(11)NOT NULL
);

CREATE TABLE Atendimentos
(
	IdAtendimento	INT PRIMARY KEY IDENTITY
	,IdPet	INT FOREIGN KEY REFERENCES Pets(IdPet)NOT NULL
	,IdVeterinario INT FOREIGN KEY REFERENCES Veterinarios(IdVeterinario)NOT NULL
	,Servico	VARCHAR(200)NOT NULL
	,DataAtendimento	DATE NOT NULL
	,ValorConsulta	SMALLMONEY NOT NULL
);

DROP TABLE Atendimentos;

DROP TABLE Veterinarios;