CREATE DATABASE Optus;

USE Optus;

CREATE TABLE Estilos
(
	IdEstilo	INT PRIMARY KEY IDENTITY
	,Nome	VARCHAR(50)NOT NULL
);

CREATE TABLE Artistas
(
	IdArtista	INT PRIMARY KEY IDENTITY
	,Nome	VARCHAR(50)NOT NULL
);

CREATE TABLE Albuns
(
	IdAlbuns	INT PRIMARY KEY IDENTITY
	,IdEstilo	INT FOREIGN KEY REFERENCES Estilos(IdEstilo)NOT NULL
	,IdArtista	INT FOREIGN KEY REFERENCES Albuns(IdAlbuns)NOT NULL
	,Titulo		VARCHAR(50)NOT NULL
	,DataLancamento	DATE NOT NULL
	,Localizacao	VARCHAR(50)NOT NULL
	,Minutos	VARCHAR(10)NOT NULL
	,Vizualizacao BIT NOT NULL
);

CREATE TABLE TipoDeUsuarios
(
	IdTipoDeUsuario		INT PRIMARY KEY IDENTITY
	,Descricao	VARCHAR(100)NOT NULL
);

CREATE TABLE Usuarios
(
	IdUsuario	INT PRIMARY KEY IDENTITY
	,IdTipoDeUsuario INT FOREIGN KEY REFERENCES TipoDeUsuarios(IdTipoDeUsuario) NOT NULL
	,Nome VARCHAR(50)
	,Email VARCHAR(70)
	,Senha VARCHAR(50)
);

